AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS solution to deploy tag automatically EKS resources (EC2 Fanilly) with MAP2.0
Resources:
  CWECatcher:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "EKS AutoScaling creation catcher"
      EventPattern:
        source:
          - "aws.autoscaling"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "autoscaling.amazonaws.com"
          userIdentity:
            invokedBy:
              - "eks-nodegroup.amazonaws.com"
      State: "ENABLED"
      Targets:
        - Arn: 'arn:aws:sns:eu-west-1:026158001388:SecOps'
          Id: 'SNSTarget'
  #LambdaPermission: 
  #Type: AWS::Lambda::Permission
  #Properties: 
    #FunctionName: 
    #Action: "lambda:InvokeFunction"
    #Principal: "events.amazonaws.com"
    #SourceArn: 
      #Fn::GetAtt: 
        #- "EventRule"
        #- "Arn"